service: test-project 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  users:
    handler: functions/handler.users
    events:
      - http: 
          path: /users
          method: GET

  user:
    handler: functions/handler.user
    events:
      - http: 
          path: /user
          method: GET
          authorizer: userAuth
          
  userAuth:
    handler: middleware/user.verifyToken

plugins:
  - serverless-offline