service: test-project 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  users:
    handler: functions/handler.index
    events:
      - http: 
          path: /numu-family/users
          method: ANY
      - http:
          path: /numu-family/user
          method: ANY
          authorizer: userAuth

  userAuth:
    handler: middleware/user.verifyToken

plugins:
  - serverless-offline