service: test-authorizers-project

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  users:
    handler: functions/handler.index
    events:
      - http: 
          path: /numu-family/users
          method: ANY
      - http:
          path: /numu-family/user
          method: ANY
          authorizer:
            name: userAuth
            identitySource: method.request.header.Authorization

  userAuth:
    handler: middleware/user.verifyToken

plugins:
  - serverless-offline
  - serverless-dotenv-plugin